name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1   # your AWS region

    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/scale.pem
        chmod 600 ~/.ssh/scale.pem

    - name: Deploy app to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/scale.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p ~/app"
        scp -o StrictHostKeyChecking=no -i ~/.ssh/scale.pem -r ./backend/* ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/app/
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/scale.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} "cd ~/app && npm install && pm2 restart all || pm2 start server.js"
